name: 'RPM Build'
description: 'Build RPMs from spec file and upload it as Artifact or Release Asset'
author: 'Naveenraj M'

inputs: 
  make_path:
    description: 'The path to the Makefile'
    required: true                     #Any spec file in top 
  additional_packages:
    description: 'A list of additional packages to install in the build container'
    required: false
  additional_definitions:
    description: 'A list of additional definitions to pass to the rpmbuild'
    required: false
  github_token:
    description: 'A github token to pass to Make'
    required: false
  make_version:
    description: 'Version string to pass to Make'
    required: false
  make_release:
    description: 'Release string to pass to Make'
    required: false

outputs:
  source_rpm_path:
    description: 'path to Source RPM file'
  source_rpm_dir_path:
    description: 'path to  SRPMS directory'
  source_rpm_name:
    description: 'name of Source RPM file'
  rpm_dir_path:
    description: 'path to RPMS directory'
  rpm_content_type:
    description: 'Content-type for Upload'

runs:
  using: 'docker'
  image: 'docker://registry.kaltura.io/library/rpmbuild-action:latest'

branding:
  icon: 'package'
  color: 'red'

  
